spring:
  application:
    name: "notificationservice"
  cloud:
    function:
      definition: email
    stream:
      bindings:
        email-in-0:
          destination: send-email
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8088

